/**
 * Shadow : Helix Nebula (SHN) — Canonical Error Codes
 *
 * Enforces API-INV-14: Machine-readable fail-closed error taxonomy.
 */

export const ErrorCode = {
  // Authentication & Authorization (BC-IAM)
  AUTH_UNAUTHENTICATED: 'ERR_AUTH_UNAUTHENTICATED',
  AUTH_FORBIDDEN: 'ERR_AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'ERR_AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'ERR_AUTH_TOKEN_INVALID',
  AUTH_MFA_REQUIRED: 'ERR_AUTH_MFA_REQUIRED',
  AUTH_ACCOUNT_DISABLED: 'ERR_AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_REVOKED: 'ERR_AUTH_ACCOUNT_REVOKED',
  AUTH_ACCOUNT_LOCKED: 'ERR_AUTH_ACCOUNT_LOCKED',
  AUTH_CREDENTIALS_INVALID: 'ERR_AUTH_CREDENTIALS_INVALID',
  AUTH_SESSION_REVOKED: 'ERR_AUTH_SESSION_REVOKED',
  AUTH_CROSS_WORKSPACE_DENIED: 'ERR_AUTH_CROSS_WORKSPACE_DENIED',
  AUTH_CROSS_ORG_DENIED: 'ERR_AUTH_CROSS_ORG_DENIED',

  // Secrets Vault & Cryptography (BC-SEC)
  VAULT_SECRET_NOT_FOUND: 'ERR_VAULT_SECRET_NOT_FOUND',
  VAULT_SECRET_REVOKED: 'ERR_VAULT_SECRET_REVOKED',
  VAULT_SECRET_DISABLED: 'ERR_VAULT_SECRET_DISABLED',
  VAULT_SECRET_EXPIRED: 'ERR_VAULT_SECRET_EXPIRED',
  VAULT_VERSION_NOT_FOUND: 'ERR_VAULT_VERSION_NOT_FOUND',
  VAULT_DECRYPTION_FAILED: 'ERR_VAULT_DECRYPTION_FAILED',
  VAULT_KEY_INVALID: 'ERR_VAULT_KEY_INVALID',

  // Scope & Boundary Enforcement (BC-SCP)
  SCOPE_VIOLATION_OUT_OF_BOUNDS: 'ERR_SCOPE_VIOLATION_OUT_OF_BOUNDS',
  SCOPE_METADATA_PROHIBITED: 'ERR_SCOPE_METADATA_PROHIBITED',
  SCOPE_WINDOW_CLOSED: 'ERR_SCOPE_WINDOW_CLOSED',
  SCOPE_MALFORMED: 'ERR_SCOPE_MALFORMED',
  SCOPE_TAMPERED: 'ERR_SCOPE_TAMPERED',
  SCOPE_TOKEN_INVALID: 'ERR_SCOPE_TOKEN_INVALID',
  SCOPE_TOKEN_EXPIRED: 'ERR_SCOPE_TOKEN_EXPIRED',
  SCOPE_ACTION_DISALLOWED: 'ERR_SCOPE_ACTION_DISALLOWED',
  SCOPE_PORT_DISALLOWED: 'ERR_SCOPE_PORT_DISALLOWED',

  // Workflow & Orchestration (BC-WFO)
  WORKFLOW_CYCLE_DETECTED: 'ERR_WORKFLOW_CYCLE_DETECTED',
  WORKFLOW_STEP_FAILED: 'ERR_WORKFLOW_STEP_FAILED',
  WORKFLOW_APPROVAL_REQUIRED: 'ERR_WORKFLOW_APPROVAL_REQUIRED',
  WORKFLOW_TERMINATED: 'ERR_WORKFLOW_TERMINATED',

  // Execution & Tool Isolation (BC-EXE, BC-CAP)
  EXEC_PROCESS_CRASH: 'ERR_EXEC_PROCESS_CRASH',
  EXEC_TIMEOUT_EXCEEDED: 'ERR_EXEC_TIMEOUT_EXCEEDED',
  EXEC_SANDBOX_BREACH: 'ERR_EXEC_SANDBOX_BREACH',
  EXEC_COMMAND_INJECTION_REJECTED: 'ERR_EXEC_COMMAND_INJECTION_REJECTED',
  EXEC_OUTPUT_LIMIT_EXCEEDED: 'ERR_EXEC_OUTPUT_LIMIT_EXCEEDED',
  EXEC_PROTOCOL_VIOLATION: 'ERR_EXEC_PROTOCOL_VIOLATION',
  EXEC_INVALID_STATE_TRANSITION: 'ERR_EXEC_INVALID_STATE_TRANSITION',
  EXEC_CANCELLED: 'ERR_EXEC_CANCELLED',
  EXEC_RESOURCE_EXHAUSTED: 'ERR_EXEC_RESOURCE_EXHAUSTED',

  // Storage & Persistence (Data Plane)
  STORAGE_NOT_FOUND: 'ERR_STORAGE_NOT_FOUND',
  STORAGE_INTEGRITY_MISMATCH: 'ERR_STORAGE_INTEGRITY_MISMATCH',
  STORAGE_CONCURRENCY_CONFLICT: 'ERR_STORAGE_CONCURRENCY_CONFLICT',
  STORAGE_TRANSACTION_FAILED: 'ERR_STORAGE_TRANSACTION_FAILED',

  // Rate Limiting & Abuse Protection
  RATE_LIMIT_EXCEEDED: 'ERR_RATE_LIMIT_EXCEEDED',
  TARGET_RATE_LIMIT_EXCEEDED: 'ERR_TARGET_RATE_LIMIT_EXCEEDED',

  // Input Validation & System Integrity
  INVALID_PAYLOAD_SCHEMA: 'ERR_INVALID_PAYLOAD_SCHEMA',
  IDEMPOTENCY_CONFLICT: 'ERR_IDEMPOTENCY_CONFLICT',
  INTERNAL_FAULT: 'ERR_INTERNAL_FAULT',
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];
