/**
 * Shadow : Helix Nebula (SHN) — RFC 7807 Problem Details Standard
 *
 * Enforces API-INV-14: Machine-readable fail-closed error contracts.
 */

import { ErrorCode, type ErrorCodeType } from './codes.js';

export interface InvalidParam {
  readonly name: string;
  readonly reason: string;
  readonly value?: string | number | boolean | null;
}

export interface ProblemDetails {
  /** A URI reference that identifies the problem type */
  readonly type: string;
  /** A short, human-readable summary of the problem type */
  readonly title: string;
  /** The HTTP status code generated by the origin server */
  readonly status: number;
  /** A human-readable explanation specific to this occurrence */
  readonly detail: string;
  /** A URI reference that identifies the specific occurrence of the problem */
  readonly instance: string;
  /** Canonical SHN machine-readable error code */
  readonly error_code: ErrorCodeType;
  /** UTC ISO 8601 timestamp of occurrence */
  readonly timestamp: string;
  /** OpenTelemetry / Distributed root transaction identifier */
  readonly correlation_id: string;
  /** Optional parameter-level validation errors */
  readonly invalid_params?: readonly InvalidParam[];
}

export interface CreateProblemOptions {
  errorCode: ErrorCodeType;
  detail: string;
  instance: string;
  correlationId: string;
  invalidParams?: readonly InvalidParam[];
  customStatus?: number;
}

const DEFAULT_ERROR_METADATA: Record<ErrorCodeType, { status: number; title: string }> = {
  [ErrorCode.AUTH_UNAUTHENTICATED]: { status: 401, title: 'Authentication Required' },
  [ErrorCode.AUTH_FORBIDDEN]: { status: 403, title: 'Access Forbidden' },
  [ErrorCode.AUTH_TOKEN_EXPIRED]: { status: 401, title: 'Security Token Expired' },
  [ErrorCode.AUTH_TOKEN_INVALID]: { status: 401, title: 'Security Token Invalid' },
  [ErrorCode.AUTH_MFA_REQUIRED]: { status: 403, title: 'Multi-Factor Authentication Required' },

  [ErrorCode.SCOPE_VIOLATION_OUT_OF_BOUNDS]: { status: 403, title: 'Target Scope Violation' },
  [ErrorCode.SCOPE_METADATA_PROHIBITED]: { status: 403, title: 'Prohibited Target Metadata IP' },
  [ErrorCode.SCOPE_WINDOW_CLOSED]: { status: 403, title: 'Operational Time Window Closed' },
  [ErrorCode.SCOPE_MALFORMED]: { status: 400, title: 'Malformed Target Scope Specification' },
  [ErrorCode.SCOPE_TAMPERED]: { status: 403, title: 'Scope Token Hash Tampering Detected' },

  [ErrorCode.WORKFLOW_CYCLE_DETECTED]: { status: 422, title: 'Invalid Cyclic Workflow Topology' },
  [ErrorCode.WORKFLOW_STEP_FAILED]: { status: 500, title: 'Workflow Step Execution Failure' },
  [ErrorCode.WORKFLOW_APPROVAL_REQUIRED]: { status: 403, title: 'Human Approval Barrier Required' },
  [ErrorCode.WORKFLOW_TERMINATED]: { status: 410, title: 'Workflow Forcefully Terminated' },

  [ErrorCode.EXEC_PROCESS_CRASH]: { status: 500, title: 'Tool Subprocess Crashed' },
  [ErrorCode.EXEC_TIMEOUT_EXCEEDED]: { status: 504, title: 'Tool Execution Timeout Ceilings Exceeded' },
  [ErrorCode.EXEC_SANDBOX_BREACH]: { status: 500, title: 'Sandbox Boundary Security Breach' },
  [ErrorCode.EXEC_COMMAND_INJECTION_REJECTED]: { status: 400, title: 'Command Injection Syntax Rejected' },

  [ErrorCode.STORAGE_NOT_FOUND]: { status: 404, title: 'Requested Resource Not Found' },
  [ErrorCode.STORAGE_INTEGRITY_MISMATCH]: { status: 500, title: 'Cryptographic Evidence Integrity Mismatch' },
  [ErrorCode.STORAGE_CONCURRENCY_CONFLICT]: { status: 409, title: 'Optimistic Concurrency State Conflict' },
  [ErrorCode.STORAGE_TRANSACTION_FAILED]: { status: 500, title: 'Relational ACID Transaction Failed' },

  [ErrorCode.RATE_LIMIT_EXCEEDED]: { status: 429, title: 'Platform Rate Limit Exceeded' },
  [ErrorCode.TARGET_RATE_LIMIT_EXCEEDED]: { status: 429, title: 'Target Rate Limit Exceeded' },

  [ErrorCode.INVALID_PAYLOAD_SCHEMA]: { status: 400, title: 'Schema Validation Failure' },
  [ErrorCode.IDEMPOTENCY_CONFLICT]: { status: 409, title: 'Idempotent Command In Flight' },
  [ErrorCode.INTERNAL_FAULT]: { status: 500, title: 'Internal System Fault' },
};

/**
 * Creates an RFC 7807 compliant ProblemDetails structure.
 * Guaranteed zero raw exception or stack trace leakage.
 */
export function createProblemDetails(options: CreateProblemOptions): ProblemDetails {
  const metadata = DEFAULT_ERROR_METADATA[options.errorCode] ?? {
    status: 500,
    title: 'Internal System Error',
  };

  const problem: ProblemDetails = {
    type: `https://api.shadow-helix-nebula.io/errors/${options.errorCode}`,
    title: metadata.title,
    status: options.customStatus ?? metadata.status,
    detail: options.detail,
    instance: options.instance,
    error_code: options.errorCode,
    timestamp: new Date().toISOString(),
    correlation_id: options.correlationId,
    ...(options.invalidParams && options.invalidParams.length > 0
      ? { invalid_params: options.invalidParams }
      : {}),
  };

  return Object.freeze(problem);
}
